channels:
  - conda-forge
dependencies:
  - catch2
  - cmake
  - doxygen
  - fmt
  - gmatelastoplasticqpot
  - goosefem
  - h5py
  - highfive
  - mathjax
  - matplotlib
  - ninja
  - numpy
  - pip
  - python
  - python-gmatelastoplasticqpot
  - python-gmattensor
  - python-goosefem
  - pyxtensor
  - setuptools_scm
  - xtensor
  - xtensor-python
