channels:
  - conda-forge
dependencies:
  # dependencies
  - xtensor
  - goosefem
  - gmatelastoplasticqpot

  # optional dependencies
  # - xsimd

  # build tools
  - cmake
  - ninja
  - setuptools_scm

  # Python API
  - python
  - pip
  - pyxtensor

  # run tests
  - catch2
  - python-goosefem
  - python-gmattensor
  - python-gmatelastoplasticqpot
  - numpy

  # run examples
  - fmt
  - highfive
  - h5py
  - matplotlib

  # build docs
  - doxygen
  - mathjax
